---
- hosts: bastion
  vars:
    tomcat_dir: "apache-tomcat-8.5.6"
    tomcat_url: "http://apache.rediris.es/tomcat/tomcat-8/v8.5.6/bin/apache-tomcat-8.5.6.tar.gz"
  become: true
  tasks:
    - name: "configure locale"
      lineinfile:
        dest: "/etc/locale.conf"
        line: "LANG=es_ES.UTF-8"
        regexp: "^LANG="

    - name: "configure timezone"
      timezone:
        name: "Europe/Madrid"

    - name: "install openjdk"
      yum:
        name: "java-1.8.0-openjdk"
        state: "installed"

    - name: "create tomcat group"
      group:
        name: "tomcat"
        state: "present"

    - name: "create tomcat user"
      user:
        name: "tomcat"
        state: "present"
        group: "tomcat"

    - name: "download tomcat"
      unarchive:
        src: "{{tomcat_url}}"
        remote_src: yes
        dest: "/opt/"
        owner: "tomcat"
        group: "tomcat"

    - name: "copy tomcat service config"
      template:
        src: "tomcat.service.j2"
        dest: "/etc/systemd/system/tomcat.service"
        mode: "0755"
        owner: "root"
        group: "root"

    - name: "install sample war"
      copy:
        src: "sample.war"
        dest: "/opt/tomcat/webapps"
        owner: "tomcat"
        group: "tomcat"
      notify: "restart tomcat"
  handlers:
    - name: "restart tomcat"
      systemd:
        daemon_reload: yes
        name: "tomcat"
        state: "restarted"

