---
- hosts: bastion
  vars:
    node_dir: "node-v6.9.1-linux-x64"
    node_url: "https://nodejs.org/dist/v6.9.1/node-v6.9.1-linux-x64.tar.xz"
  become: true
  tasks:
    - name: "configure locale"
      lineinfile:
        dest: "/etc/locale.conf"
        line: "LANG=es_ES.UTF-8"
        regexp: "^LANG="

    - name: "configure timezone"
      timezone:
        name: "Europe/Madrid"

    - name: "install openjdk"
      yum:
        name: "java-1.8.0-openjdk"
        state: "installed"

    - name: "download nodejs"
      unarchive:
        src: "{{node_url}}"
        remote_src: yes
        dest: "/opt/"
        owner: "root"
        group: "root"

    - name: "link nodejs dir"
      file:
        state: "link"
        src: "/opt/{{node_dir}}"
        dest: "/opt/node"

    - name: "link nodejs bin"
      file:
        state: "link"
        src: "/opt/{{node_dir}}/bin/node"
        dest: "/usr/bin/node"

    - name: "create node user"
      user:
        name: "node"
        state: "present"

