---
- hosts: bastion
  become: true
  tasks:
    - name: "configure locale"
      lineinfile:
        dest: "/etc/locale.conf"
        line: "LANG=es_ES.UTF-8"
        regexp: "^LANG="

    - name: "configure timezone"
      timezone:
        name: "Europe/Madrid"

    - name: "install openjdk"
      yum:
        name: "java-1.8.0-openjdk"
        state: "installed"

    # - name: "install node"

    # - name: "node user"

