---
- hosts: bastion
  vars_files:
    - vars/main.yml
  become: true

  roles:
    - { role: "roles/devops.locale" }
    - { role: "roles/devops.timezone" }
    - { role: "roles/devops.openjdk" }

  tasks:
    - name: "download nodejs"
      unarchive:
        src: "{{node_url}}"
        remote_src: yes
        dest: "/opt/"
        owner: "root"
        group: "root"

    - name: "link nodejs dir"
      file:
        state: "link"
        src: "/opt/{{node_dir}}"
        dest: "/opt/node"

    - name: "link nodejs bin"
      file:
        state: "link"
        src: "/opt/{{node_dir}}/bin/node"
        dest: "/usr/bin/node"

    - name: "create node user"
      user:
        name: "node"
        state: "present"

